<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reflection.proto

namespace Crayoon\HyperfGrpc\Reflection;

/**
 * Protobuf type <code>grpc.reflection.v1alpha.ServerReflection</code>
 */
interface ServerReflectionInterface
{
    /**
     * The reflection service is structured as a bidirectional stream, ensuring
     * all related requests go to a single server.
     *
     * Method <code>serverReflectionInfo</code>
     *
     * @param \Crayoon\HyperfGrpc\Reflection\ServerReflectionRequest $request
     * @return \Crayoon\HyperfGrpc\Reflection\ServerReflectionResponse
     */
    public function serverReflectionInfo(\Crayoon\HyperfGrpc\Reflection\ServerReflectionRequest $request);

}

